basic:
    name: 'Alojamento Universitário'
    environments:
        production: 'https://fctunl.portalalojamentouniversitario.pt/'
        staging: 'https://alojamentoprod.dev11.javali.pt/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - ofertas-mapa
        - user/register
        - user/login
        - imovel/quanto-em-apartamento-1-km
        - imovel/quartos-disponivel-rooms-available
        - imovel/apartamento-novo-almada-centro-ac-smart-tv-cleaning-and-laudring
        - imovel/quarto-junto-fct
        - imovel/quartos-individuais-estudantes-universitarios-almada
        - terms-conditions
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
